org.gradle.jvmargs=-Xmx4G
android.useAndroidX=true
android.enableJetifier=true
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
# Avoid corrupted/duplicated Kotlin incremental-cache registrations on Windows.
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
